site: Situated
url: https://situated.blog
title: Situated
description: Spurious thoughts on ethics, engineering and the web.
author:
  name: Sean Voisen
twitter:
  username: svoisen
  card: summary

permalink: pretty

paginate: 1000
paginate_path: "/page:num/"
baseurl: ""
  
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir: _sass
  style: :compressed

plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap  

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - 
    scope:
      path: "assets/images"
    values:
      image: true
